name: Code quality

on: [push]

jobs:
  isort:
    name: Import sorting (isort)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: isort/isort-action@v0.1.0
        with:
          requirementsFiles: requirements/ci.txt
          sortPaths: "src docs"
          configuration: '--check-only --diff'

  black:
    name: Code formatting (black)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          pip install -r requirements/ci.txt
      - name: Run black
        run: |
          black --check src docs

  flake8:
    name: Code style (flake8)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          pip install -r requirements/ci.txt
      - name: Run flake8
        run: |
          flake8 src
